### ISSUE TITLE
Tracking: 1.21 port

### ISSUE THREAD

**Issue by o7Moon** [o7Moon/OpenBoatUtils#65]
- [x] port to [stonecutter](https://stonecutter.kikugie.dev/)
- [x] sanity test on 1.20.1-1.20.4 to make sure everything works
- [x] support new networking on 1.21, and have it match 1.20.X so existing plugins don't need any changes
